services:
  - type: web
    name: rfid-tracking-app
    env: java
    rootDir: ChallengeJavaSprint4
    buildCommand: "mvn clean package -DskipTests -Dspring.datasource.url=jdbc:postgresql://localhost/postgres"
    startCommand: "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/project-sprint4-1.0.0.jar"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rfid-tracking-db
          property: connectionString
    autoDeploy: true

databases:
  - name: rfid-tracking-db
    databaseName: rfid_tracking
    user: rfid_user
